---
title: "Fundação ABC"
# subtitle: "Sous-titre"
author: "Embrapa Arroz e Feijão"
date: "`r format(Sys.time(), '%d de %B, %Y \n %H:%M:%S ')`"
always_allow_html: yes
# toc: true
---



```{css, echo=FALSE}
    h1,h4{text-align:center;
          font-weight: bold;
          color: rgb(255,255,255);
    }
    
.container-fluid.main-container {border-style: groove;}

    div#header{
          
  background-color: rgb(0,102,153);
  background-image: linear-gradient(to bottom right, rgb(0,102,153), rgb(0,153,102));
    
   
    
    }
    
    caption{text-align:center;
          color: black;
          font-weight: bold;
          font-size: 35px;
          }
          
    header{
    border-style: solid;
          background: rgb(204,204,204);
    }
      
    thead{text-align:center;
      background: rgb(76,175,80);
      border-style: solid;
    }
    
```



```{r, echo=FALSE}
criarInfomacoes = function(){
  variaveis = data.frame(
    Variaveis = c(
      "Cultura",
      "Safra",
      "Estado",
      "Cidade",
      "irrigacao",
      "Fungicida",
      "Tipo de grao",
      "Epoca"
    ),
    Selecionados = c(
       input$culturaInputDoencas,
       input$safraInputDoencas,
       input$estadoInputDoencas,
       input$cidadeInputDoencas,
       input$irrigacaoInputDoencas,
       input$fungicidaInputDoencas,
       input$tipodegraoInputDoencas,
       input$epocaInputDoencas
    ),
    stringsAsFactors = F
  )
  return(variaveis)
  
}

kable(criarInfomacoes(), caption = "Variáveis selecionadas")
  
```

Data

```{r, echo=FALSE, warning = FALSE, verify_fa = FALSE}
dadosGenotipos = service.getY(dadosFiltrados(), TRUE)


options(DT.options = list(pageLength = 5, language = list(search = 'Filter:'), scrollX = TRUE))

dadosGenotipos = dadosGenotipos[,c("gid","year", "y")]
colnames(dadosGenotipos) <- c("Cultivar","Ano", " Media(BLUP)")                                

dadosGenotipos = as.data.frame(dadosGenotipos) 
                         

#dadosGenotipos = dadosGenotipos[order(dadosGenotipos$mean,decreasing = T),]
DT::datatable(dadosGenotipos)
         
          

```
